### ISSUE TITLE
pretrained embedding 

### ISSUE THREAD

**Issue by M0hammadL** [HelloWorldLTY/MuSe-GNN#1]
hi 

congratulation for the nice work, I was wondering if you have an object for gene embeddings you have trained across all tissues which people can use for down stream similar to g2vec.

**Comment by HelloWorldLTY** [comment]
Hi Mo, thanks for your interests. Sorry for my late reply because I am preparing my slides and materials for the camera ready version. I am happy to provide the gene embeddings we have for multiple tissues. (https://github.com/HelloWorldLTY/MuSe-GNN/tree/main/demodata)

The anndata file we just uploaded contains genes as instances, and in the observation section, we had gene names, tissue name, as well as its dataset source. Notice that we believe genes from different tissues have different functions, so they should have different embeddings.

If you have any questions, I am happy to discuss more about it.
